// Generated by gencpp from file msgs_1515/Collision_Debug.msg
// DO NOT EDIT!


#ifndef MSGS_1515_MESSAGE_COLLISION_DEBUG_H
#define MSGS_1515_MESSAGE_COLLISION_DEBUG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <msgs_1515/Collision_Object.h>
#include <msgs_1515/Collision_Object.h>

namespace msgs_1515
{
template <class ContainerAllocator>
struct Collision_Debug_
{
  typedef Collision_Debug_<ContainerAllocator> Type;

  Collision_Debug_()
    : header()
    , seq(0)
    , stamp()
    , frame_id()
    , LaggingObj()
    , LeadingObj()
    , LowerLimit(0.0)
    , UpperLimit(0.0)  {
    }
  Collision_Debug_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , seq(0)
    , stamp()
    , frame_id(_alloc)
    , LaggingObj(_alloc)
    , LeadingObj(_alloc)
    , LowerLimit(0.0)
    , UpperLimit(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _seq_type;
  _seq_type seq;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef  ::msgs_1515::Collision_Object_<ContainerAllocator>  _LaggingObj_type;
  _LaggingObj_type LaggingObj;

   typedef  ::msgs_1515::Collision_Object_<ContainerAllocator>  _LeadingObj_type;
  _LeadingObj_type LeadingObj;

   typedef float _LowerLimit_type;
  _LowerLimit_type LowerLimit;

   typedef float _UpperLimit_type;
  _UpperLimit_type UpperLimit;





  typedef boost::shared_ptr< ::msgs_1515::Collision_Debug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_1515::Collision_Debug_<ContainerAllocator> const> ConstPtr;

}; // struct Collision_Debug_

typedef ::msgs_1515::Collision_Debug_<std::allocator<void> > Collision_Debug;

typedef boost::shared_ptr< ::msgs_1515::Collision_Debug > Collision_DebugPtr;
typedef boost::shared_ptr< ::msgs_1515::Collision_Debug const> Collision_DebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_1515::Collision_Debug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_1515::Collision_Debug_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_1515::Collision_Debug_<ContainerAllocator1> & lhs, const ::msgs_1515::Collision_Debug_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.seq == rhs.seq &&
    lhs.stamp == rhs.stamp &&
    lhs.frame_id == rhs.frame_id &&
    lhs.LaggingObj == rhs.LaggingObj &&
    lhs.LeadingObj == rhs.LeadingObj &&
    lhs.LowerLimit == rhs.LowerLimit &&
    lhs.UpperLimit == rhs.UpperLimit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_1515::Collision_Debug_<ContainerAllocator1> & lhs, const ::msgs_1515::Collision_Debug_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_1515

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::Collision_Debug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::Collision_Debug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::Collision_Debug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::Collision_Debug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::Collision_Debug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::Collision_Debug_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_1515::Collision_Debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03f9ad5ff762f269d1f7b61bc1ae9977";
  }

  static const char* value(const ::msgs_1515::Collision_Debug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03f9ad5ff762f269ULL;
  static const uint64_t static_value2 = 0xd1f7b61bc1ae9977ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_1515::Collision_Debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_1515/Collision_Debug";
  }

  static const char* value(const ::msgs_1515::Collision_Debug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_1515::Collision_Debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"  uint32 seq\n"
"  time stamp\n"
"  string frame_id\n"
"Collision_Object LaggingObj\n"
"Collision_Object LeadingObj\n"
"float32 LowerLimit\n"
"float32 UpperLimit\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: msgs_1515/Collision_Object\n"
"float32 xPos\n"
"float32 yPos\n"
"float32 speed\n"
;
  }

  static const char* value(const ::msgs_1515::Collision_Debug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_1515::Collision_Debug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.seq);
      stream.next(m.stamp);
      stream.next(m.frame_id);
      stream.next(m.LaggingObj);
      stream.next(m.LeadingObj);
      stream.next(m.LowerLimit);
      stream.next(m.UpperLimit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Collision_Debug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_1515::Collision_Debug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_1515::Collision_Debug_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "LaggingObj: ";
    s << std::endl;
    Printer< ::msgs_1515::Collision_Object_<ContainerAllocator> >::stream(s, indent + "  ", v.LaggingObj);
    s << indent << "LeadingObj: ";
    s << std::endl;
    Printer< ::msgs_1515::Collision_Object_<ContainerAllocator> >::stream(s, indent + "  ", v.LeadingObj);
    s << indent << "LowerLimit: ";
    Printer<float>::stream(s, indent + "  ", v.LowerLimit);
    s << indent << "UpperLimit: ";
    Printer<float>::stream(s, indent + "  ", v.UpperLimit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_1515_MESSAGE_COLLISION_DEBUG_H
