// Generated by gencpp from file msgs_1515/ContiRadar.msg
// DO NOT EDIT!


#ifndef MSGS_1515_MESSAGE_CONTIRADAR_H
#define MSGS_1515_MESSAGE_CONTIRADAR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msgs_1515
{
template <class ContainerAllocator>
struct ContiRadar_
{
  typedef ContiRadar_<ContainerAllocator> Type;

  ContiRadar_()
    : header()
    , obstacle_id(0)
    , longitude_dist(0.0)
    , lateral_dist(0.0)
    , longitude_vel(0.0)
    , lateral_vel(0.0)
    , rcs(0.0)
    , orientation_angle(0.0)
    , length(0.0)
    , width(0.0)
    , prob_exist(0.0)
    , obstacle_class()
    , dyn_property()
    , meas_state(0)  {
    }
  ContiRadar_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacle_id(0)
    , longitude_dist(0.0)
    , lateral_dist(0.0)
    , longitude_vel(0.0)
    , lateral_vel(0.0)
    , rcs(0.0)
    , orientation_angle(0.0)
    , length(0.0)
    , width(0.0)
    , prob_exist(0.0)
    , obstacle_class(_alloc)
    , dyn_property(_alloc)
    , meas_state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _obstacle_id_type;
  _obstacle_id_type obstacle_id;

   typedef float _longitude_dist_type;
  _longitude_dist_type longitude_dist;

   typedef float _lateral_dist_type;
  _lateral_dist_type lateral_dist;

   typedef float _longitude_vel_type;
  _longitude_vel_type longitude_vel;

   typedef float _lateral_vel_type;
  _lateral_vel_type lateral_vel;

   typedef float _rcs_type;
  _rcs_type rcs;

   typedef float _orientation_angle_type;
  _orientation_angle_type orientation_angle;

   typedef float _length_type;
  _length_type length;

   typedef float _width_type;
  _width_type width;

   typedef float _prob_exist_type;
  _prob_exist_type prob_exist;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _obstacle_class_type;
  _obstacle_class_type obstacle_class;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dyn_property_type;
  _dyn_property_type dyn_property;

   typedef uint8_t _meas_state_type;
  _meas_state_type meas_state;





  typedef boost::shared_ptr< ::msgs_1515::ContiRadar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_1515::ContiRadar_<ContainerAllocator> const> ConstPtr;

}; // struct ContiRadar_

typedef ::msgs_1515::ContiRadar_<std::allocator<void> > ContiRadar;

typedef boost::shared_ptr< ::msgs_1515::ContiRadar > ContiRadarPtr;
typedef boost::shared_ptr< ::msgs_1515::ContiRadar const> ContiRadarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_1515::ContiRadar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_1515::ContiRadar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_1515::ContiRadar_<ContainerAllocator1> & lhs, const ::msgs_1515::ContiRadar_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacle_id == rhs.obstacle_id &&
    lhs.longitude_dist == rhs.longitude_dist &&
    lhs.lateral_dist == rhs.lateral_dist &&
    lhs.longitude_vel == rhs.longitude_vel &&
    lhs.lateral_vel == rhs.lateral_vel &&
    lhs.rcs == rhs.rcs &&
    lhs.orientation_angle == rhs.orientation_angle &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.prob_exist == rhs.prob_exist &&
    lhs.obstacle_class == rhs.obstacle_class &&
    lhs.dyn_property == rhs.dyn_property &&
    lhs.meas_state == rhs.meas_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_1515::ContiRadar_<ContainerAllocator1> & lhs, const ::msgs_1515::ContiRadar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_1515

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::ContiRadar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::ContiRadar_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::ContiRadar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::ContiRadar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::ContiRadar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::ContiRadar_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_1515::ContiRadar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54fd2f5dc0ec9b28d9901950018b93fb";
  }

  static const char* value(const ::msgs_1515::ContiRadar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54fd2f5dc0ec9b28ULL;
  static const uint64_t static_value2 = 0xd9901950018b93fbULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_1515::ContiRadar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_1515/ContiRadar";
  }

  static const char* value(const ::msgs_1515::ContiRadar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_1515::ContiRadar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 obstacle_id\n"
"float32 longitude_dist\n"
"float32 lateral_dist\n"
"float32 longitude_vel\n"
"float32 lateral_vel\n"
"float32 rcs\n"
"float32 orientation_angle\n"
"float32 length\n"
"float32 width\n"
"float32 prob_exist\n"
"string obstacle_class\n"
"string dyn_property\n"
"uint8 meas_state\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msgs_1515::ContiRadar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_1515::ContiRadar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacle_id);
      stream.next(m.longitude_dist);
      stream.next(m.lateral_dist);
      stream.next(m.longitude_vel);
      stream.next(m.lateral_vel);
      stream.next(m.rcs);
      stream.next(m.orientation_angle);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.prob_exist);
      stream.next(m.obstacle_class);
      stream.next(m.dyn_property);
      stream.next(m.meas_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContiRadar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_1515::ContiRadar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_1515::ContiRadar_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obstacle_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacle_id);
    s << indent << "longitude_dist: ";
    Printer<float>::stream(s, indent + "  ", v.longitude_dist);
    s << indent << "lateral_dist: ";
    Printer<float>::stream(s, indent + "  ", v.lateral_dist);
    s << indent << "longitude_vel: ";
    Printer<float>::stream(s, indent + "  ", v.longitude_vel);
    s << indent << "lateral_vel: ";
    Printer<float>::stream(s, indent + "  ", v.lateral_vel);
    s << indent << "rcs: ";
    Printer<float>::stream(s, indent + "  ", v.rcs);
    s << indent << "orientation_angle: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_angle);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "prob_exist: ";
    Printer<float>::stream(s, indent + "  ", v.prob_exist);
    s << indent << "obstacle_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.obstacle_class);
    s << indent << "dyn_property: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dyn_property);
    s << indent << "meas_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.meas_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_1515_MESSAGE_CONTIRADAR_H
