// Generated by gencpp from file msgs_1515/Decision.msg
// DO NOT EDIT!


#ifndef MSGS_1515_MESSAGE_DECISION_H
#define MSGS_1515_MESSAGE_DECISION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msgs_1515
{
template <class ContainerAllocator>
struct Decision_
{
  typedef Decision_<ContainerAllocator> Type;

  Decision_()
    : header()
    , seq(0)
    , stamp()
    , frame_id()
    , action(0)
    , lane_values()  {
    }
  Decision_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , seq(0)
    , stamp()
    , frame_id(_alloc)
    , action(0)
    , lane_values(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _seq_type;
  _seq_type seq;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _action_type;
  _action_type action;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _lane_values_type;
  _lane_values_type lane_values;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ACTION_LEFT_LANE_CHANGE)
  #undef ACTION_LEFT_LANE_CHANGE
#endif
#if defined(_WIN32) && defined(ACTION_LANE_KEEP)
  #undef ACTION_LANE_KEEP
#endif
#if defined(_WIN32) && defined(ACTION_RIGHT_LANE_CHANGE)
  #undef ACTION_RIGHT_LANE_CHANGE
#endif

  enum {
    ACTION_LEFT_LANE_CHANGE = 0u,
    ACTION_LANE_KEEP = 1u,
    ACTION_RIGHT_LANE_CHANGE = 2u,
  };


  typedef boost::shared_ptr< ::msgs_1515::Decision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_1515::Decision_<ContainerAllocator> const> ConstPtr;

}; // struct Decision_

typedef ::msgs_1515::Decision_<std::allocator<void> > Decision;

typedef boost::shared_ptr< ::msgs_1515::Decision > DecisionPtr;
typedef boost::shared_ptr< ::msgs_1515::Decision const> DecisionConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_1515::Decision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_1515::Decision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_1515::Decision_<ContainerAllocator1> & lhs, const ::msgs_1515::Decision_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.seq == rhs.seq &&
    lhs.stamp == rhs.stamp &&
    lhs.frame_id == rhs.frame_id &&
    lhs.action == rhs.action &&
    lhs.lane_values == rhs.lane_values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_1515::Decision_<ContainerAllocator1> & lhs, const ::msgs_1515::Decision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_1515

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::Decision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::Decision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::Decision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::Decision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::Decision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::Decision_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_1515::Decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "769e9c4a24bdd40723b6cd29194c3ea5";
  }

  static const char* value(const ::msgs_1515::Decision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x769e9c4a24bdd407ULL;
  static const uint64_t static_value2 = 0x23b6cd29194c3ea5ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_1515::Decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_1515/Decision";
  }

  static const char* value(const ::msgs_1515::Decision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_1515::Decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"  uint32 seq\n"
"  time stamp\n"
"  string frame_id\n"
"uint8 action\n"
"uint8 ACTION_LEFT_LANE_CHANGE=0\n"
"uint8 ACTION_LANE_KEEP=1\n"
"uint8 ACTION_RIGHT_LANE_CHANGE=2\n"
"float32[] lane_values\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msgs_1515::Decision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_1515::Decision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.seq);
      stream.next(m.stamp);
      stream.next(m.frame_id);
      stream.next(m.action);
      stream.next(m.lane_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Decision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_1515::Decision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_1515::Decision_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "lane_values[]" << std::endl;
    for (size_t i = 0; i < v.lane_values.size(); ++i)
    {
      s << indent << "  lane_values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lane_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_1515_MESSAGE_DECISION_H
