// Generated by gencpp from file msgs_1515/FaultList.msg
// DO NOT EDIT!


#ifndef MSGS_1515_MESSAGE_FAULTLIST_H
#define MSGS_1515_MESSAGE_FAULTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <msgs_1515/BayesianList.h>

namespace msgs_1515
{
template <class ContainerAllocator>
struct FaultList_
{
  typedef FaultList_<ContainerAllocator> Type;

  FaultList_()
    : header()
    , bayesian_output()  {
    }
  FaultList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bayesian_output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::msgs_1515::BayesianList_<ContainerAllocator>  _bayesian_output_type;
  _bayesian_output_type bayesian_output;





  typedef boost::shared_ptr< ::msgs_1515::FaultList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_1515::FaultList_<ContainerAllocator> const> ConstPtr;

}; // struct FaultList_

typedef ::msgs_1515::FaultList_<std::allocator<void> > FaultList;

typedef boost::shared_ptr< ::msgs_1515::FaultList > FaultListPtr;
typedef boost::shared_ptr< ::msgs_1515::FaultList const> FaultListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_1515::FaultList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_1515::FaultList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_1515::FaultList_<ContainerAllocator1> & lhs, const ::msgs_1515::FaultList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bayesian_output == rhs.bayesian_output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_1515::FaultList_<ContainerAllocator1> & lhs, const ::msgs_1515::FaultList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_1515

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::FaultList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::FaultList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::FaultList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::FaultList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::FaultList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::FaultList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_1515::FaultList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59bf514a4899a92e7dbc72149c0662a2";
  }

  static const char* value(const ::msgs_1515::FaultList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59bf514a4899a92eULL;
  static const uint64_t static_value2 = 0x7dbc72149c0662a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_1515::FaultList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_1515/FaultList";
  }

  static const char* value(const ::msgs_1515::FaultList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_1515::FaultList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"msgs_1515/BayesianList bayesian_output\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: msgs_1515/BayesianList\n"
"uint8 Q1\n"
"uint8 Q2\n"
"uint8 Q3\n"
"uint8 Q4\n"
"uint8 Q5\n"
"uint8 Q6\n"
"uint8 Q7\n"
"uint8 Q8\n"
"uint8 Q9\n"
"uint8 Q10\n"
;
  }

  static const char* value(const ::msgs_1515::FaultList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_1515::FaultList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bayesian_output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaultList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_1515::FaultList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_1515::FaultList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bayesian_output: ";
    s << std::endl;
    Printer< ::msgs_1515::BayesianList_<ContainerAllocator> >::stream(s, indent + "  ", v.bayesian_output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_1515_MESSAGE_FAULTLIST_H
