// Generated by gencpp from file msgs_1515/Obstacle.msg
// DO NOT EDIT!


#ifndef MSGS_1515_MESSAGE_OBSTACLE_H
#define MSGS_1515_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msgs_1515/ObstacleKinematics.h>
#include <msgs_1515/ObstacleProperties.h>

namespace msgs_1515
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : obstacle_kinematics()
    , obstacle_properties()  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : obstacle_kinematics(_alloc)
    , obstacle_properties(_alloc)  {
  (void)_alloc;
    }



   typedef  ::msgs_1515::ObstacleKinematics_<ContainerAllocator>  _obstacle_kinematics_type;
  _obstacle_kinematics_type obstacle_kinematics;

   typedef  ::msgs_1515::ObstacleProperties_<ContainerAllocator>  _obstacle_properties_type;
  _obstacle_properties_type obstacle_properties;





  typedef boost::shared_ptr< ::msgs_1515::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_1515::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::msgs_1515::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::msgs_1515::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::msgs_1515::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_1515::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_1515::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_1515::Obstacle_<ContainerAllocator1> & lhs, const ::msgs_1515::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle_kinematics == rhs.obstacle_kinematics &&
    lhs.obstacle_properties == rhs.obstacle_properties;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_1515::Obstacle_<ContainerAllocator1> & lhs, const ::msgs_1515::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_1515

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_1515::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dc5d4ef897e9d201b15e7e0c351f4a7";
  }

  static const char* value(const ::msgs_1515::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dc5d4ef897e9d20ULL;
  static const uint64_t static_value2 = 0x1b15e7e0c351f4a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_1515::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_1515/Obstacle";
  }

  static const char* value(const ::msgs_1515::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_1515::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_1515/ObstacleKinematics obstacle_kinematics\n"
"msgs_1515/ObstacleProperties obstacle_properties\n"
"================================================================================\n"
"MSG: msgs_1515/ObstacleKinematics\n"
"std_msgs/Header header\n"
"  uint32 seq\n"
"  time stamp\n"
"  string frame_id\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist twist\n"
"geometry_msgs/Accel accel\n"
"geometry_msgs/Vector3 dimensions\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: msgs_1515/ObstacleProperties\n"
"uint8 blinker_info\n"
"uint8 cut_in_and_out\n"
"uint8 obstacle_type\n"
"uint8 obstacle_status\n"
"bool obstacle_brake_lights\n"
"uint8 obstacle_valid\n"
"uint16 obstacle_age\n"
"uint8 obstacle_lane\n"
"bool cipv_flag\n"
"float32 radar_pos_x\n"
"float32 radar_vel_x\n"
"uint8 radar_match_confidence\n"
"uint16 matched_radar_id\n"
"float64 obstacle_scale_change\n"
"bool obstacle_replaced\n"
"uint8 radar_obstacle_id\n"
"uint16 me_obstacle_id\n"
"float32 rcs\n"
"float32 prob_exist\n"
"string obstacle_class\n"
"string dyn_property\n"
"uint8 meas_state\n"
"uint16 track_id\n"
"uint8 track_status\n"
"float64 prbty_exstn\n"
"float64 prbty_prsntn\n"
"float64 prbty_detn\n"
"float64 prbty_clutr\n"
"float64[] covariance\n"
"float64[] R\n"
;
  }

  static const char* value(const ::msgs_1515::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_1515::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle_kinematics);
      stream.next(m.obstacle_properties);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_1515::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_1515::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "obstacle_kinematics: ";
    s << std::endl;
    Printer< ::msgs_1515::ObstacleKinematics_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacle_kinematics);
    s << indent << "obstacle_properties: ";
    s << std::endl;
    Printer< ::msgs_1515::ObstacleProperties_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacle_properties);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_1515_MESSAGE_OBSTACLE_H
