// Generated by gencpp from file msgs_1515/TSLR_BBoxs.msg
// DO NOT EDIT!


#ifndef MSGS_1515_MESSAGE_TSLR_BBOXS_H
#define MSGS_1515_MESSAGE_TSLR_BBOXS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <msgs_1515/TSLR_BBox.h>
#include <msgs_1515/TSLR_SpdLim.h>

namespace msgs_1515
{
template <class ContainerAllocator>
struct TSLR_BBoxs_
{
  typedef TSLR_BBoxs_<ContainerAllocator> Type;

  TSLR_BBoxs_()
    : header()
    , image_header()
    , bounding_boxes()
    , SpdLim()  {
    }
  TSLR_BBoxs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , bounding_boxes(_alloc)
    , SpdLim(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::msgs_1515::TSLR_BBox_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msgs_1515::TSLR_BBox_<ContainerAllocator> >> _bounding_boxes_type;
  _bounding_boxes_type bounding_boxes;

   typedef  ::msgs_1515::TSLR_SpdLim_<ContainerAllocator>  _SpdLim_type;
  _SpdLim_type SpdLim;





  typedef boost::shared_ptr< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> const> ConstPtr;

}; // struct TSLR_BBoxs_

typedef ::msgs_1515::TSLR_BBoxs_<std::allocator<void> > TSLR_BBoxs;

typedef boost::shared_ptr< ::msgs_1515::TSLR_BBoxs > TSLR_BBoxsPtr;
typedef boost::shared_ptr< ::msgs_1515::TSLR_BBoxs const> TSLR_BBoxsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator1> & lhs, const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image_header == rhs.image_header &&
    lhs.bounding_boxes == rhs.bounding_boxes &&
    lhs.SpdLim == rhs.SpdLim;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator1> & lhs, const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_1515

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dc90c36e2ae03bcd05954534edf078f";
  }

  static const char* value(const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dc90c36e2ae03bcULL;
  static const uint64_t static_value2 = 0xd05954534edf078fULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_1515/TSLR_BBoxs";
  }

  static const char* value(const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# TSLR Bouinding Boxes\n"
"Header header\n"
"Header image_header\n"
"TSLR_BBox[] bounding_boxes\n"
"TSLR_SpdLim SpdLim\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: msgs_1515/TSLR_BBox\n"
"# TSLR Bouinding Boxes\n"
"int64 Class\n"
"float64 probability # between 0 and 1\n"
"# int64 xmin\n"
"# int64 ymin\n"
"# int64 xmax\n"
"# int64 ymax\n"
"# bool IsSpeedSign\n"
"int64 SpeedSignValue\n"
"float64 ETA # second\n"
"\n"
"================================================================================\n"
"MSG: msgs_1515/TSLR_SpdLim\n"
"# TSLR Speed limit information. This will be used by ACC in order to limit ego vehicle's speed.\n"
"int64 speed_limit\n"
;
  }

  static const char* value(const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.bounding_boxes);
      stream.next(m.SpdLim);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TSLR_BBoxs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_1515::TSLR_BBoxs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_1515::TSLR_BBoxs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "bounding_boxes[]" << std::endl;
    for (size_t i = 0; i < v.bounding_boxes.size(); ++i)
    {
      s << indent << "  bounding_boxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msgs_1515::TSLR_BBox_<ContainerAllocator> >::stream(s, indent + "    ", v.bounding_boxes[i]);
    }
    s << indent << "SpdLim: ";
    s << std::endl;
    Printer< ::msgs_1515::TSLR_SpdLim_<ContainerAllocator> >::stream(s, indent + "  ", v.SpdLim);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_1515_MESSAGE_TSLR_BBOXS_H
