// Generated by gencpp from file msgs_1515/Waypoint.msg
// DO NOT EDIT!


#ifndef MSGS_1515_MESSAGE_WAYPOINT_H
#define MSGS_1515_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgs_1515
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : index(0)
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , speed(0.0)  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : index(0)
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _index_type;
  _index_type index;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::msgs_1515::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_1515::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::msgs_1515::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::msgs_1515::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::msgs_1515::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgs_1515::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgs_1515::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgs_1515::Waypoint_<ContainerAllocator1> & lhs, const ::msgs_1515::Waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgs_1515::Waypoint_<ContainerAllocator1> & lhs, const ::msgs_1515::Waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgs_1515

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgs_1515::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgs_1515::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgs_1515::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgs_1515::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51172f33ab183ce15ce692336bb9149a";
  }

  static const char* value(const ::msgs_1515::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51172f33ab183ce1ULL;
  static const uint64_t static_value2 = 0x5ce692336bb9149aULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_1515::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgs_1515/Waypoint";
  }

  static const char* value(const ::msgs_1515::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgs_1515::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 index\n"
"float32 x\n"
"float32 y\n"
"float32 yaw\n"
"float32 speed\n"
;
  }

  static const char* value(const ::msgs_1515::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgs_1515::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_1515::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgs_1515::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.index);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_1515_MESSAGE_WAYPOINT_H
