(cl:in-package msgs_1515-msg)
(cl:export '(BLINKER_INFO-VAL
          BLINKER_INFO
          CUT_IN_AND_OUT-VAL
          CUT_IN_AND_OUT
          OBSTACLE_TYPE-VAL
          OBSTACLE_TYPE
          OBSTACLE_STATUS-VAL
          OBSTACLE_STATUS
          OBSTACLE_BRAKE_LIGHTS-VAL
          OBSTACLE_BRAKE_LIGHTS
          OBSTACLE_VALID-VAL
          OBSTACLE_VALID
          OBSTACLE_AGE-VAL
          OBSTACLE_AGE
          OBSTACLE_LANE-VAL
          OBSTACLE_LANE
          CIPV_FLAG-VAL
          CIPV_FLAG
          RADAR_POS_X-VAL
          RADAR_POS_X
          RADAR_VEL_X-VAL
          RADAR_VEL_X
          RADAR_MATCH_CONFIDENCE-VAL
          RADAR_MATCH_CONFIDENCE
          MATCHED_RADAR_ID-VAL
          MATCHED_RADAR_ID
          OBSTACLE_SCALE_CHANGE-VAL
          OBSTACLE_SCALE_CHANGE
          OBSTACLE_REPLACED-VAL
          OBSTACLE_REPLACED
          RADAR_OBSTACLE_ID-VAL
          RADAR_OBSTACLE_ID
          ME_OBSTACLE_ID-VAL
          ME_OBSTACLE_ID
          RCS-VAL
          RCS
          PROB_EXIST-VAL
          PROB_EXIST
          OBSTACLE_CLASS-VAL
          OBSTACLE_CLASS
          DYN_PROPERTY-VAL
          DYN_PROPERTY
          MEAS_STATE-VAL
          MEAS_STATE
          TRACK_ID-VAL
          TRACK_ID
          TRACK_STATUS-VAL
          TRACK_STATUS
          PRBTY_EXSTN-VAL
          PRBTY_EXSTN
          PRBTY_PRSNTN-VAL
          PRBTY_PRSNTN
          PRBTY_DETN-VAL
          PRBTY_DETN
          PRBTY_CLUTR-VAL
          PRBTY_CLUTR
          COVARIANCE-VAL
          COVARIANCE
          R-VAL
          R
))