(cl:in-package msgs_1515-msg)
(cl:export '(HEADER-VAL
          HEADER
          OBSTACLE_ID-VAL
          OBSTACLE_ID
          LONGITUDE_DIST-VAL
          LONGITUDE_DIST
          LATERAL_DIST-VAL
          LATERAL_DIST
          LONGITUDE_VEL-VAL
          LONGITUDE_VEL
          LATERAL_VEL-VAL
          LATERAL_VEL
          RCS-VAL
          RCS
          ORIENTATION_ANGLE-VAL
          ORIENTATION_ANGLE
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          PROB_EXIST-VAL
          PROB_EXIST
          OBSTACLE_CLASS-VAL
          OBSTACLE_CLASS
          DYN_PROPERTY-VAL
          DYN_PROPERTY
          MEAS_STATE-VAL
          MEAS_STATE
))