(cl:in-package msgs_1515-msg)
(cl:export '(HEADER-VAL
          HEADER
          TARGET_ID-VAL
          TARGET_ID
          LONGITUDE_DIST-VAL
          LONGITUDE_DIST
          LATERAL_DIST-VAL
          LATERAL_DIST
          LONGITUDE_VEL-VAL
          LONGITUDE_VEL
          LATERAL_VEL-VAL
          LATERAL_VEL
          RCS-VAL
          RCS
          DYNPROP-VAL
          DYNPROP
          STD_DEV_LONG_DIST-VAL
          STD_DEV_LONG_DIST
          STD_DEV_LAT_DIST-VAL
          STD_DEV_LAT_DIST
          STD_DEV_LONG_VEL-VAL
          STD_DEV_LONG_VEL
          STD_DEV_LAT_VEL-VAL
          STD_DEV_LAT_VEL
          FALSE_ALARM_PROB-VAL
          FALSE_ALARM_PROB
          VALIDTY_STATE-VAL
          VALIDTY_STATE
          DOPPLER_STATE-VAL
          DOPPLER_STATE
          STATIC_CHECK-VAL
          STATIC_CHECK
))