# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msgs_1515/AutonomousStates.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class AutonomousStates(genpy.Message):
  _md5sum = "c16518f721ec6e01d4ec26824c39854c"
  _type = "msgs_1515/AutonomousStates"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
std_msgs/Bool lka_status
std_msgs/Int8 acc_status
std_msgs/Int8 acc_mode
std_msgs/Int8 set_speed
std_msgs/Int8 dm_mode
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: std_msgs/Bool
bool data
================================================================================
MSG: std_msgs/Int8
int8 data
"""
  __slots__ = ['header','seq','stamp','frame_id','lka_status','acc_status','acc_mode','set_speed','dm_mode']
  _slot_types = ['std_msgs/Header','uint32','time','string','std_msgs/Bool','std_msgs/Int8','std_msgs/Int8','std_msgs/Int8','std_msgs/Int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,seq,stamp,frame_id,lka_status,acc_status,acc_mode,set_speed,dm_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AutonomousStates, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.seq is None:
        self.seq = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.frame_id is None:
        self.frame_id = ''
      if self.lka_status is None:
        self.lka_status = std_msgs.msg.Bool()
      if self.acc_status is None:
        self.acc_status = std_msgs.msg.Int8()
      if self.acc_mode is None:
        self.acc_mode = std_msgs.msg.Int8()
      if self.set_speed is None:
        self.set_speed = std_msgs.msg.Int8()
      if self.dm_mode is None:
        self.dm_mode = std_msgs.msg.Int8()
    else:
      self.header = std_msgs.msg.Header()
      self.seq = 0
      self.stamp = genpy.Time()
      self.frame_id = ''
      self.lka_status = std_msgs.msg.Bool()
      self.acc_status = std_msgs.msg.Int8()
      self.acc_mode = std_msgs.msg.Int8()
      self.set_speed = std_msgs.msg.Int8()
      self.dm_mode = std_msgs.msg.Int8()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.seq, _x.stamp.secs, _x.stamp.nsecs))
      _x = self.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B4b().pack(_x.lka_status.data, _x.acc_status.data, _x.acc_mode.data, _x.set_speed.data, _x.dm_mode.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.lka_status is None:
        self.lka_status = std_msgs.msg.Bool()
      if self.acc_status is None:
        self.acc_status = std_msgs.msg.Int8()
      if self.acc_mode is None:
        self.acc_mode = std_msgs.msg.Int8()
      if self.set_speed is None:
        self.set_speed = std_msgs.msg.Int8()
      if self.dm_mode is None:
        self.dm_mode = std_msgs.msg.Int8()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.seq, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.lka_status.data, _x.acc_status.data, _x.acc_mode.data, _x.set_speed.data, _x.dm_mode.data,) = _get_struct_B4b().unpack(str[start:end])
      self.lka_status.data = bool(self.lka_status.data)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.seq, _x.stamp.secs, _x.stamp.nsecs))
      _x = self.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B4b().pack(_x.lka_status.data, _x.acc_status.data, _x.acc_mode.data, _x.set_speed.data, _x.dm_mode.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.lka_status is None:
        self.lka_status = std_msgs.msg.Bool()
      if self.acc_status is None:
        self.acc_status = std_msgs.msg.Int8()
      if self.acc_mode is None:
        self.acc_mode = std_msgs.msg.Int8()
      if self.set_speed is None:
        self.set_speed = std_msgs.msg.Int8()
      if self.dm_mode is None:
        self.dm_mode = std_msgs.msg.Int8()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.seq, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.lka_status.data, _x.acc_status.data, _x.acc_mode.data, _x.set_speed.data, _x.dm_mode.data,) = _get_struct_B4b().unpack(str[start:end])
      self.lka_status.data = bool(self.lka_status.data)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B4b = None
def _get_struct_B4b():
    global _struct_B4b
    if _struct_B4b is None:
        _struct_B4b = struct.Struct("<B4b")
    return _struct_B4b
